CREATE TABLE IF NOT EXISTS job_applications (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  s_no INTEGER UNIQUE,
  application_date DATE NOT NULL,
  company_name TEXT NOT NULL,
  profession_applied TEXT,
  job_title TEXT,
  industry_sector TEXT,
  source TEXT,
  job_link TEXT,
  recruiter_name TEXT,
  recruiter_contact TEXT,
  referral_name TEXT,
  application_status TEXT NOT NULL DEFAULT 'Applied',
  days_since_applied INTEGER
);

CREATE INDEX IF NOT EXISTS job_applications_application_date_idx
  ON job_applications (application_date DESC);

CREATE INDEX IF NOT EXISTS job_applications_application_status_idx
  ON job_applications (application_status);
